### ISSUE TITLE
大佬好

### ISSUE THREAD

**Issue by WuJingLearn** [luanlengli/aliyun-rds-exporter#1]
大佬好，想要收集rds的一些监控信息，阿里云有暴露这样的api供我们调用吗，我找不到 ，求告知

**Comment by luanlengli** [comment]
阿里云RDS文档
https://help.aliyun.com/document_detail/26279.html?spm=a2c4g.11174283.6.1774.49255b83zWhpgM
阿里云RDS的OpenAPI开发文档
https://api.aliyun.com/#/?product=Rds
